# Generated by Django 4.0.4 on 2022-05-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_buildings_address_building'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'building')},
        ),
    ]
