# Generated by Django 4.0.4 on 2022-05-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('name', 'address')},
        ),
    ]
